_schema-version: "3.3"
ID: EMPLOYEE1-CAP
version: 1.0.0

parameters:
  enable-parallel-deployments: true

build-parameters:
  before-all:
    - builder: custom
      commands:
        - npm install
        - npx cds build --production

modules:

  - name: EMPLOYEE1-CAP-srv
    type: nodejs
    path: gen/srv

    parameters:
      memory: 512M
      disk-quota: 512M

    provides:
      - name: srv-api
        properties:
          srv-url: ${default-url}

    requires:
      - name: EMPLOYEE1-CAP-db
      - name: EMPLOYEE1-CAP-xsuaa
      - name: EMPLOYEE1-CAP-destination

    build-parameters:
      builder: npm-ci

  - name: EMPLOYEE1-CAP-db-deployer
    type: hdb
    path: gen/db

    requires:
      - name: EMPLOYEE1-CAP-db

resources:

  - name: EMPLOYEE1-CAP-db
    type: com.sap.xs.hdi-container
    parameters:
      service: hana
      service-plan: hdi-shared

  - name: EMPLOYEE1-CAP-xsuaa
    type: org.cloudfoundry.managed-service
    parameters:
      service: xsuaa
      service-plan: application
      path: xs-security.json

  - name: EMPLOYEE1-CAP-destination
    type: org.cloudfoundry.managed-service
    parameters:
      service: destination
      service-plan: lite
